### ISSUE TITLE
Python binding test fails

### ISSUE THREAD

**Issue by mmurooka** [jrl-umi3218/Tasks#72]
When installing mc_rtc according to [tutorial](https://jrl-umi3218.github.io/mc_rtc/tutorials/introduction/installation-guide.html), the error occurs in the python binding test of Tasks.

OS is Ubuntu 16.04.

All log: [build_and_install_warnings-2020-11-17-13-07-12.log](https://github.com/jrl-umi3218/Tasks/files/5551246/build_and_install_warnings-2020-11-17-13-07-12.log)

Extract only the part related to the error:
```
    Start 5: test-tasks-python-bindings

5: Test command: /usr/local/bin/cmake "-E" "env" "LD_LIBRARY_PATH=/home/mmurooka/jrl/Tasks/build/src:/opt/ros/kinetic/share/euslisp/jskeus/eus//Linux64/lib:/home/mmurooka/jrl/catkin_ws/devel/lib:/home/mmurooka/jrl/catkin_data_ws/devel/lib:/opt/ros/kinetic/lib:/opt/ros/kinetic/lib/x86_64-linux-gnu:/opt/ros/kinetic/share/euslisp/jskeus/eus//Linux64/lib:/opt/ros/kinetic/share/euslisp/jskeus/eus//Linux64/lib:/home/mmurooka/jrl/install/lib:/home/mmurooka/openrtp/lib:/home/mmurooka/openrtp/share/DynamoRIO-Linux-6.2.0-2/ext/lib64/release:/home/mmurooka/ros/kinetic_parent/devel/share/euslisp/jskeus/eus//Linux64/lib:/home/mmurooka/jrl/install/lib:/home/mmurooka/install/lib:/usr/lib/nvidia-440:/usr/local/cuda/lib64" "/usr/local/bin/cmake" "-E" "env" "PYTHONPATH=.:/opt/ros/kinetic/lib/python2.7/dist-packages:/home/mmurooka/jrl/install/lib/python2.7/site-packages:/home/mmurooka/openrtp/lib/python2.7/dist-packages/hrpsys:/home/mmurooka/jrl/install/lib/python2.7/site-packages:/home/mmurooka/install/lib/python2.7/site-packages" "/usr/local/bin/cmake" "-E" "chdir" "/home/mmurooka/jrl/Tasks/build/binding/python/tasks/python/RelWithDebInfo" "python" "-c" "import nose, sys; sys.exit(not nose.run())"
5: Test timeout computed to be: 1500
5: EE
5: ======================================================================
5: ERROR: Failure: ValueError (rbdyn.rbdyn.Jacobian has the wrong size, try recompiling)
5: ----------------------------------------------------------------------
5: Traceback (most recent call last):
5:   File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 418, in loadTestsFromName
5:     addr.filename, addr.module)
5:   File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 47, in importFromPath
5:     return self.importFromDir(dir_path, fqname)
5:   File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 94, in importFromDir
5:     mod = load_module(part_fqname, fh, filename, desc)
5:   File "/home/mmurooka/jrl/Tasks/build/binding/python/tasks/python/RelWithDebInfo/tasks/__init__.py", line 1, in <module>
5:     from . tasks import *
5:   File "rbdyn.pxd", line 69, in init tasks.tasks (tasks/tasks.cpp:38354)
5: ValueError: rbdyn.rbdyn.Jacobian has the wrong size, try recompiling
5: 
5: ======================================================================
5: ERROR: Failure: ValueError (rbdyn.rbdyn.Jacobian has the wrong size, try recompiling)
5: ----------------------------------------------------------------------
5: Traceback (most recent call last):
5:   File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 418, in loadTestsFromName
5:     addr.filename, addr.module)
5:   File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 47, in importFromPath
5:     return self.importFromDir(dir_path, fqname)
5:   File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 94, in importFromDir
5:     mod = load_module(part_fqname, fh, filename, desc)
5:   File "/home/mmurooka/jrl/Tasks/build/binding/python/tasks/python/RelWithDebInfo/tests/TestQPMultiRobot.py", line 24, in <module>
5:     import tasks
5:   File "tasks/__init__.py", line 2, in <module>
5:     from . import qp
5:   File "tasks/qp/__init__.py", line 1, in <module>
5:     from .qp import *
5:   File "rbdyn.pxd", line 69, in init tasks.qp.qp (tasks/qp/qp.cpp:97731)
5: ValueError: rbdyn.rbdyn.Jacobian has the wrong size, try recompiling
5: 
5: ----------------------------------------------------------------------
5: Ran 2 tests in 0.084s
5: 
5: FAILED (errors=2)
5/5 Test #5: test-tasks-python-bindings .......***Failed    0.41 sec

80% tests passed, 1 tests failed out of 5

Total Test time (real) =   1.66 sec

The following tests FAILED:
	  5 - test-tasks-python-bindings (Failed)
Errors while running CTest
-- [ERROR] Testing is still failing for jrl-umi3218/Tasks, please investigate deeper
Installation failed.
Installation log has been written to /tmp/build_and_install_warnings-2020-11-17-13-07-12.log
Please fix the issues and re-run the script.
```

**Comment by gergondet** [comment]
Hi @mmurooka 

This is an incremental issue update, the RBDyn bindings have to be rebuilt and then the Tasks bindings have to be rebuilt, i.e.:

```bash
cd $HOME/jrl/RBDyn/build
make force-rbdyn-python-bindings
sudo make install
cd $HOME/jrl/Tasks/build
make force-tasks-python-bindings
sudo make install
make test
```

**Comment by mmurooka** [comment]
Thank you. I tried your rebuild commands, but the test still fails..

```
mmurooka@mmurooka-ThinkPad-P53:~/jrl/Tasks/build$ LANG=C make test
Running tests...
/usr/local/bin/ctest --force-new-ctest-process 
Test project /home/mmurooka/jrl/Tasks/build
    Start 1: QPSolverTestUnit
1/5 Test #1: QPSolverTestUnit .................   Passed    1.03 sec
    Start 2: QPMultiRobotTestUnit
2/5 Test #2: QPMultiRobotTestUnit .............   Passed    0.19 sec
    Start 3: TasksTestUnit
3/5 Test #3: TasksTestUnit ....................   Passed    0.02 sec
    Start 4: AllocationTestUnit
4/5 Test #4: AllocationTestUnit ...............   Passed    0.01 sec
    Start 5: test-tasks-python-bindings
5/5 Test #5: test-tasks-python-bindings .......***Failed    0.42 sec

80% tests passed, 1 tests failed out of 5

Total Test time (real) =   1.66 sec

The following tests FAILED:
	  5 - test-tasks-python-bindings (Failed)
Errors while running CTest
Makefile:83: recipe for target 'test' failed
make: *** [test] Error 8
```

(I don't use python-binding for the time being, so I completed the installation with `export WITH_PYTHON_SUPPORT="false"`. So, resolving this issue is not urgent now.)

**Comment by mmurooka** [comment]
The problem seems to be due to the Python version.

Python binding is installed to the `~/.local/lib/python3.5`, but maybe `python2.7` is used in the tests. As a result, the RBDyn python binding used in the tests remains unupdated.

Since the default version of system python in Ubuntu 16.04 is 2.7, I think the correct direction is to modify the install destination of python binding to `~/.local/lib/python2.7`.
(But this is just a problem only for those who continue to use old Ubuntu.)

```bash
$ locate c_rbdyn.pxd | grep -v mc_rbdyn | xargs ls --full-time
-rw-rw-r-- 1 mmurooka mmurooka 12786 2020-05-16 17:44:47.144518000 +0900 /home/mmurooka/.local/lib/python2.7/site-packages/rbdyn/c_rbdyn.pxd
-rw-rw-r-- 1 mmurooka mmurooka 12786 2020-11-17 18:46:26.009440660 +0900 /home/mmurooka/.local/lib/python3.5/site-packages/rbdyn/c_rbdyn.pxd
-rw-rw-r-- 1 mmurooka mmurooka 12786 2020-11-17 13:07:46.992087934 +0900 /home/mmurooka/jrl/RBDyn/binding/python/rbdyn/c_rbdyn.pxd
-rw-rw-r-- 1 mmurooka mmurooka 12786 2020-11-17 13:12:34.847099905 +0900 /home/mmurooka/jrl/RBDyn/build/binding/python/rbdyn/python/RelWithDebInfo/rbdyn/c_rbdyn.pxd
# /home/mmurooka/.local/lib/python2.7/site-packages/rbdyn/c_rbdyn.pxd is old.

$ python --version
Python 2.7.12
```

**Comment by mmurooka** [comment]
Versions of python and pip are not consistent in my environment,
```
$ which python
/usr/bin/python
$ which pip
/home/mmurooka/.local/bin/pip
$ python --version
Python 2.7.12
$ pip --version
pip 20.1.1 from /home/mmurooka/.local/lib/python3.5/site-packages/pip (python 3.5)
```

I don't understand the following part well,
https://github.com/jrl-umi3218/jrl-cmakemodules/blob/master/cython/cython.cmake#L151-L182
but,  maybe this is the cause of the incorrect installation destination.

**Comment by gergondet** [comment]
@mmurooka Thanks for looking deeper into it.

That's the issue indeed. It is assumed that `python` and `pip` refer to the same version but unfortunately this is not effectively enforced or even checked.

By default, the build and installation of the bindings will be performed via `pip` calls while the tests will run with `python`

There's an option in mc_rtc build-script to enforce the use of `python2`/`pip2` (and/or `python3`/`pip3`)

**Comment by mmurooka** [comment]
With `PYTHON_FORCE_PYTHON2` true, the installation with python binding was succeeded.
I close this issue by taking over the matter about script improvements to https://github.com/jrl-umi3218/mc_rtc/issues/90.
